EVALUATE
VAR EndDate = DATE(2024, 9, 29)  // Adjust the end date here

VAR FilteredTable = TOPN(7,
    FILTER(
        SUMMARIZE(hcp_appointments,[Start Date]),
        hcp_appointments[Start Date] <= EndDate
    ),[Start Date], DESC)

VAR SummarizedTable = 
    SUMMARIZE(
        FilteredTable,
        hcp_appointments[Start Date],
        "Sum_WdDirect", [#_WdDirect]
    )
	
var asd = 
AVERAGEX(SummarizedTable,[Sum_WdDirect])
RETURN
SummarizedTable--ROW("Avera",asd)