DEFINE
    VAR _DateLimit = DATE(2024, 9, 29)

EVALUATE
    ROW(
        "PreAllocAVG%_CC_VCs",
        CALCULATE(
            AVERAGEX(
                SUMMARIZE(
                    hcp_appointments,
                    hcp_appointments[Start Date],
                    "MeasureValue", [#_WdCorporate]
                ),
                [MeasureValue]
            ),
            hcp_appointments[Start Date] <= _DateLimit
        )
    )
